# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: test

permissions: read-all

jobs:
  testit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: r-lib/actions/setup-r@ff9d3a3fd8acec17e91f1d0a1876d95ad60cb519 #v2...something
      - uses: r-lib/actions/setup-r-dependencies@ff9d3a3fd8acec17e91f1d0a1876d95ad60cb519 #v2...something
        with:
          extra-packages: github::katehayes/dQALY@89cea44e3673f06426b7a38784f421f55dcb71ac

      - name: meh
        run: install.packages('pipeline', repos = c('https://timtaylor.r-universe.dev/bin/linux/noble-x86_64/4.6', 'https://cloud.r-project.org'));source('test.R')
        shell: Rscript {0}
